// Code generated by entc, DO NOT EDIT.

package ent

import (
	"examples/repository/ent/item"
	"examples/repository/ent/order"
	"examples/repository/ent/schema"
	"examples/repository/ent/shop"
	"examples/repository/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	itemMixin := schema.Item{}.Mixin()
	itemMixinFields0 := itemMixin[0].Fields()
	_ = itemMixinFields0
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescCreateTime is the schema descriptor for create_time field.
	itemDescCreateTime := itemMixinFields0[0].Descriptor()
	// item.DefaultCreateTime holds the default value on creation for the create_time field.
	item.DefaultCreateTime = itemDescCreateTime.Default.(func() time.Time)
	// itemDescUpdateTime is the schema descriptor for update_time field.
	itemDescUpdateTime := itemMixinFields0[1].Descriptor()
	// item.DefaultUpdateTime holds the default value on creation for the update_time field.
	item.DefaultUpdateTime = itemDescUpdateTime.Default.(func() time.Time)
	// item.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	item.UpdateDefaultUpdateTime = itemDescUpdateTime.UpdateDefault.(func() time.Time)
	orderMixin := schema.Order{}.Mixin()
	orderMixinFields0 := orderMixin[0].Fields()
	_ = orderMixinFields0
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCreateTime is the schema descriptor for create_time field.
	orderDescCreateTime := orderMixinFields0[0].Descriptor()
	// order.DefaultCreateTime holds the default value on creation for the create_time field.
	order.DefaultCreateTime = orderDescCreateTime.Default.(func() time.Time)
	// orderDescUpdateTime is the schema descriptor for update_time field.
	orderDescUpdateTime := orderMixinFields0[1].Descriptor()
	// order.DefaultUpdateTime holds the default value on creation for the update_time field.
	order.DefaultUpdateTime = orderDescUpdateTime.Default.(func() time.Time)
	// order.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	order.UpdateDefaultUpdateTime = orderDescUpdateTime.UpdateDefault.(func() time.Time)
	shopMixin := schema.Shop{}.Mixin()
	shopMixinFields0 := shopMixin[0].Fields()
	_ = shopMixinFields0
	shopFields := schema.Shop{}.Fields()
	_ = shopFields
	// shopDescCreateTime is the schema descriptor for create_time field.
	shopDescCreateTime := shopMixinFields0[0].Descriptor()
	// shop.DefaultCreateTime holds the default value on creation for the create_time field.
	shop.DefaultCreateTime = shopDescCreateTime.Default.(func() time.Time)
	// shopDescUpdateTime is the schema descriptor for update_time field.
	shopDescUpdateTime := shopMixinFields0[1].Descriptor()
	// shop.DefaultUpdateTime holds the default value on creation for the update_time field.
	shop.DefaultUpdateTime = shopDescUpdateTime.Default.(func() time.Time)
	// shop.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	shop.UpdateDefaultUpdateTime = shopDescUpdateTime.UpdateDefault.(func() time.Time)
	// shopDescName is the schema descriptor for name field.
	shopDescName := shopFields[0].Descriptor()
	// shop.DefaultName holds the default value on creation for the name field.
	shop.DefaultName = shopDescName.Default.(string)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
}
