// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Shop is the predicate function for shop builders.
type Shop func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
